from .uflash import *
from .uflash import (
    _VERSION as _VERSION,
    _SCRIPT_ADDR as _SCRIPT_ADDR,
    _MICROBIT_ID_V1 as _MICROBIT_ID_V1,
    _FS_START_ADDR_V1 as _FS_START_ADDR_V1,
    _FS_END_ADDR_V1 as _FS_END_ADDR_V1,
    _MICROBIT_ID_V2 as _MICROBIT_ID_V2,
    _FS_START_ADDR_V2 as _FS_START_ADDR_V2,
    _FS_END_ADDR_V2 as _FS_END_ADDR_V2,
    _MAX_SIZE as _MAX_SIZE,
)
